---

- hosts: all
  gather_facts: no
  connection: network_cli
  vars:
    ansible_user: admin+cet
    ansible_ssh_pass: ''
    ansible_network_os: routeros
  roles:
    - ansible-role-mikrotik-hostname
